package com.example;

enum TokenType {
    //characters
    COMMA, DASH, COLON, DOT, SLASH, PERIOD, A, QUOTE,

    //constant keywords
    KEYWORD, FIRST_STRIKE, VIGILANCE, MENACE, TRAMPLE, REACH, LIFELINK, FLASH, FLYING, INDESTRUCTIBLE, 

    //variable keywords
    WARD, HEXPROOF,

    //actions
    PAY, CREATE, PUT, GAIN, GET, CAST, PREVENT, DRAW, DEAL, EQUIP, ATTACK, BLOCK, ATTACH, EXILE, SACRIFICE, DESTROY, RETURN, LOOK, REVEAL, MAY, ENCHANT, DIE, SURVEIL, SCRY, CHOOSE, SEPARATE, REMOVE, TAP, COPY, DISCARD, MILL, PLAY,
    SPEND, ACTIVATE, DOUBLE, BECOME, UNTAP, RESOLVE, SEARCH, SHUFFLE, CAUSE, LEAVE, ADD, DISTRIBUTE, CHANGE, EXCHANGE, PROLIFERATE, CYCLE, EXPLOIT, CONTAIN, MANIFEST, REMAIN, EXERT, FLIP, DISCOVER, CONNIVE, SKIP, AMASS, MOVE,
    INVESTIGATE, POPULATE, FIGHT, COLLECT_EV, SUPPORT, ESCAPE, CASCADE, 

    //attributes
    COST, HAS, 

    //events
    TARGETS, ENTERS,

    //game concepts
    LIFE, CONTROL, COMBAT, DAMAGE, WIN, LOSE, GAME, CARD, COUNTER, END, TURN, ABILITY, TRIGGER, A_DECK, MANA, VALUE, GRAVEYARD, LIBRARY, HAND, BATTLEFIELD, TOP, BOTTOM, POWER, TOUGHNESS, REST, RANDOM, ORDER, KICKED, DECK, OWNER, OWN, 
    FACEDOWN, FACEUP, PILE, EMBLEM, EXCESS, STARTING, KIND, BEGIN, SUBTYPE, COST_VALUE, EFFECT, EVERYTHING, COLOR, ACTIVATED, LOYALTY, NEW, BASE, DEVOTION, CITY_BLESS, COIN, UNSPENT,

    //logic
    WHENEVER, WHEN, WITH, THATD_BE, IF, CANT, ON, WOULD, INSTEAD, THEN, EXCEPT, UNLESS, MUST, HAS_NOT, WHERE, ABLE, OTHERWISE, 

    //groupings
    OR, AND, AND_OR,

    //references
    IT, THAT, YOU, OPPONENT, OTHER, ANOTHER, CARDNAME, SPELLNAME, TARGET, EQUIPPED, TO, EACH, UP, NAMED, BE, THE, YOUR, AMONG, THEM, ENCHANTED, PLAYER, THEY, DIFFERENT, CARDS, THEIR, SOURCE, X_VAR, ANY, CONTROLLER, ANYWHERE, _S, ONTO,
    THEY_ARE, WHO, MODIFIED,

    //timing
    DURING, UNTIL, ONCE_A_TURN, YOURTURNS, EOT, THIS, YOUR_TURN, BEGINNING, NEXT, STEP, OPENING, AT, AFTER, PHASE, UPKEEP, WHILE, BEFORE, MAIN, POSTCOMBAT,

    //checks
    WAS, IS, ONLY, CAN, CANNOT, BLOCKING, ATTACKING, FROM, AS, WAS_NOT, YOU_HAVE, ALREADY, WERE_NOT, EXACTLY, WERE,

    //quantity
    NUM, OR_MORE, OR_LESS, MORE, LESS, FOR, ALL, ANY_NUM_OF, NUM_OF, EQUAL, NUMBER, ITERATION, QUANTITY, A_NUM, MANY, MUCH, AMOUNT, LEAST, TOTAL, MAXIMUM, SIZE, STAT_BLOCK, STAT_CHANGE, ONCE, TWICE, LOYALTY_COST, X_LOYALTY, GREATEST,
    PLUS, MINUS, HALF, ROUND, DOWN, SAME, BOTH, SAGA_COUNT,

    //object properties
    SUPERTYPE, TYPE, NON, COLOR_SPEC, NAME, CHARACS,

    //vestigial
    LONG, IN, ADDITION, INTO, UNDER, THERE, ARE, THOSE, TIME, DO, THOUGH, THATS, IT_IS, RATHER, THAN, BACK, WAY, SINGLE, DO_NOT, DIVIDED, NO, STILL, UNRECOGNIZED, OF, WITHOUT, BY, PUTTING, BEEN, USING, LEFT, 
    
    LINE_END

}
