package com.example;

public enum TokenType {
    // Keywords
    KEYWORD, WHEN, WHENEVER, AT, THE, BEGINNING, OF, YOUR, EACH, OPPONENT, 
    YOU, CANNOT, COMMA, PERIOD, LINE_END, THIS, ENTERS, DIE, ATTACK, CAST,
    DRAW, DISCARD, CARD, GET, PAY, SACRIFICE, CREATE, PUT, TARGET, CHOOSE,
    RETURN, EXILE, DESTROY, TAP, UNTAP, GAIN, LOSE, DEAL, DAMAGE, EQUAL,
    TO, FROM, WITH, ON, IT, HAS, GETS, BECOME, LEAVE, CONTROL, OWNER,
    HAND, LIBRARY, BATTLEFIELD, GRAVEYARD, EXILE_ZONE, STACK, MANA, COST,
    VALUE, POWER, TOUGHNESS, STAT_CHANGE, COUNTER, COUNTERS, PLUS, MINUS,
    TIMES, DIVIDED, AMONG, THEM, THOSE, OTHER, ANOTHER, ALL, ANY, NUMBER,
    QUANTITY, AMOUNT, MUCH, MANY, LESS, MORE, OR, AND, BUT, IF, THEN, ELSE,
    UNLESS, UNTIL, WHILE, FOR, AS, LONG, INSTEAD, RATHER, THAN, ONLY,
    TWICE, ONCE, FIRST, SECOND, THIRD, NEXT, PREVIOUS, LAST, FINAL,
    
    // Supertypes
    SUPERTYPE, CREATURE, SPELL, INSTANT, SORCERY, ENCHANTMENT, ARTIFACT,
    LAND, PLANESWALKER, TOKEN, PERMANENT, BASIC, NON_BASIC,
    
    // Subtypes  
    SUBTYPE, ANGEL, DEMON, DRAGON, ELF, HUMAN, BEAST, ELEMENTAL, SPIRIT,
    ZOMBIE, SKELETON, VAMPIRE, WOLF, BEAR, CAT, DOG, BIRD, FISH, SNAKE,
    SPIDER, INSECT, WURM, HYDRA, GIANT, TROLL, GOBLIN, ORC, MERFOLK,
    VEDALKEN, KOR, LEONIN, MINOTAUR, CENTAUR, SATYR, FAUN, DRYAD, NYMPH,
    FAERIE, SPRITE, ELEMENTAL_FIRE, ELEMENTAL_WATER, ELEMENTAL_EARTH,
    ELEMENTAL_AIR, CONSTRUCT, GOLEM, SERVO, THOPTER, CLUE, FOOD, TREASURE,
    BLOOD, OIL, QUEST, SHIELD, STUN, FINALITY, COLLECTION, EXALTED,
    
    // Colors
    COLOR_SPEC, WHITE, BLUE, BLACK, RED, GREEN, COLORLESS, MULTICOLORED,
    
    // Keywords/Abilities
    FLYING, TRAMPLE, FIRST_STRIKE, DOUBLE_STRIKE, DEATHTOUCH, LIFELINK,
    VIGILANCE, REACH, HASTE, HEXPROOF, SHROUD, INDESTRUCTIBLE, PROTECTION,
    MENACE, DEFENDER, FLASH, FLASHBACK, CYCLING, KICKER, BESTOW, CONVOKE,
    AFFINITY, ANNIHILATOR, DEVOID, EMERGE, ESCAPE, LIVING_WEAPON, EQUIP,
    CREW, VEHICLE, MODULAR, FABRICATE, IMPROVISE, IMPRINT,
    MADNESS, MORBID, THRESHOLD, ASCEND, CITY_BLESSING, AFTERLIFE, MENTOR,
    ADAPT, EXPLOIT, SUPPORT, CONNIVE, COLLECT_EV, DISCOVER,
    AMASS, CASCADE, STORM, REPLICATE, OVERLOAD, ENTWINE,
    ESCALATE, ESCALATION, ESCALATION_COST, ESCALATION_TARGET,
    
    // Special tokens
    COST_VALUE, STAT_BLOCK, SAGA_COUNT, X_VAR, ITERATION, UNRECOGNIZED,
    QUOTE, DOT, DASH, COLON, SEMICOLON, PAREN_OPEN, PAREN_CLOSE,
    BRACKET_OPEN, BRACKET_CLOSE, BRACE_OPEN, BRACE_CLOSE,
    
    // Game actions
    SEARCH, REVEAL, SHUFFLE, MILL, SCRY, INVESTIGATE, MANIFEST, POPULATE,
    COUNTER_SPELL, COUNTER_ABILITY, ACTIVATE, TRIGGER,
    RESOLVE, STACK_ABILITY, STACK_SPELL, COPY, CLONE, MIRROR,
    
    // Phases and steps
    UPKEEP, DRAW_STEP, MAIN_PHASE, COMBAT_PHASE, DECLARE_ATTACKERS,
    DECLARE_BLOCKERS, COMBAT_DAMAGE, END_STEP, CLEANUP,
    COMBAT, MAIN, END, OTHERWISE,
    
    // Conditions
    MODIFIED, ENCHANTED, CREWED, TAPPED, UNTAPPED, SUMMONING_SICK,
    
    // EOF
    EOF
}